---
# Per environment values which override defaults in hmpps-staff-api/values.yaml

generic-service:
  ingress:
    host: hmpps-staff-api.hmpps.service.justice.gov.uk

  env:
    OAUTH_ENDPOINT_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
